version: '3.9'

name: ecom-campaigns-management

services:
  backend:
    build:
      context: ..
      dockerfile: deploy/backend.Dockerfile
    env_file:
      - .env
    environment:
      MONGO_URL: ${MONGO_URL}
      MONGO_DB_NAME: ${MONGO_DB_NAME:-ecom-system}
      PORT: 8080
    ports:
      - "8080:8080"
    restart: unless-stopped
    container_name: backend

  frontend:
    build:
      context: ..
      dockerfile: deploy/frontend.Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: frontend
    depends_on:
      - backend
