version: '3.9'

name: ecom-campaigns-management

services:
  backend:
    build:
      context: ..
      dockerfile: deploy/backend.Dockerfile
    env_file:
      - .env
    environment:
      MONGO_URL: ${MONGO_URL}
      MONGO_DB_NAME: ${MONGO_DB_NAME:-ecom-system}
      PORT: ${BACKEND_PORT:-8081}
    ports:
      - "8081:8081"
    restart: unless-stopped
    container_name: ecom-campaigns-management-backend

  frontend:
    build:
      context: ..
      dockerfile: deploy/frontend.Dockerfile
      args:
        VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    ports:
      - "${FRONTEND_PORT:-3001}:80"
    restart: unless-stopped
    container_name: ecom-campaigns-management-frontend
    depends_on:
      - backend

